# Generated by Django 5.1.6 on 2025-04-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_budgetdocument_document_budget_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdocument',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetdocument',
            name='file',
            field=models.FileField(upload_to='budgets/'),
        ),
    ]
