# Generated by Django 5.1.6 on 2025-04-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_budgetdocument_document_alter_budgetdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('extensionist', models.CharField(blank=True, max_length=255)),
                ('no_of_beneficiaries', models.CharField(max_length=100)),
                ('partner_agency', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.annualreport')),
            ],
        ),
    ]
