# Generated by Django 5.1.6 on 2025-04-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_annualreport_extensionactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionactivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='extensionactivity',
            name='location',
        ),
    ]
