# Generated by Django 5.1.6 on 2025-04-29 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_extensionactivity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionactivity',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extensionactivity',
            name='linkage_nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkages', to='accounts.annualreport')),
            ],
        ),
    ]
