# Generated by Django 5.1.6 on 2025-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_extensionactivity_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
