# Generated by Django 5.1.6 on 2025-04-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_annualreport_google_drive_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('target_no', models.PositiveIntegerField()),
                ('actual_male', models.PositiveIntegerField()),
                ('actual_female', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('persons_responsible', models.CharField(max_length=255)),
                ('budget_allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.quarterlyreport')),
            ],
        ),
    ]
