# Generated by Django 5.1.6 on 2025-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_quarterlyreport_extensionproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionactivity',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='extensionactivity',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='extensionactivity',
            name='linkage_nature',
        ),
        migrations.AddField(
            model_name='extensionactivity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
