# Generated by Django 5.1.6 on 2025-04-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_extensionactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='completion_doc1',
            field=models.FileField(blank=True, null=True, upload_to='documents/completion/'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='completion_doc2',
            field=models.FileField(blank=True, null=True, upload_to='documents/completion/'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='completion_doc3',
            field=models.FileField(blank=True, null=True, upload_to='documents/completion/'),
        ),
    ]
