# Generated by Django 5.1.6 on 2025-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_documentfile_completion_doc1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='budget_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='BudgetDocument',
        ),
    ]
