# Generated by Django 5.1.6 on 2025-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_document_budget_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('completion_pending', 'Completion Pending')], default='pending', max_length=20),
        ),
    ]
