# Generated by Django 5.1.6 on 2025-05-05 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_document_doc3_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='day',
            name='coordinator',
            field=models.ManyToManyField(related_name='coordinated_days', to=settings.AUTH_USER_MODEL),
        ),
    ]
