# Generated by Django 5.1.6 on 2025-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_day_coordinator_day_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'January to March'), ('Q2', 'April to June'), ('Q3', 'July to September'), ('Q4', 'October to December')], default='Q1', max_length=2),
        ),
    ]
