# Generated by Django 5.1.6 on 2025-05-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_quarterlyreport_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCompletionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_doc1', models.FileField(blank=True, null=True, upload_to='documents/day_completion/')),
                ('completion_doc2', models.FileField(blank=True, null=True, upload_to='documents/day_completion/')),
                ('completion_doc3', models.FileField(blank=True, null=True, upload_to='documents/day_completion/')),
                ('completion_doc4', models.FileField(blank=True, null=True, upload_to='documents/day_completion/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.day')),
            ],
        ),
    ]
