# Generated by Django 5.1.6 on 2025-05-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, help_text='General comment about the document.', null=True),
        ),
    ]
