# Generated by Django 5.1.6 on 2025-05-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_document_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Super Admin', 'Campus Dean'), ('Campus Admin', 'Campus Coordinator'), ('Staff Extensionist', 'Staff Extensionist'), ('Department Coordinator', 'Department Coordinator'), ('Extensionist', 'Extensionist')], max_length=50),
        ),
    ]
