# Generated by Django 5.1.6 on 2025-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionactivity',
            name='activity',
            field=models.TextField(),
        ),
    ]
