# Generated by Django 5.1.6 on 2025-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_extensionactivity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
