# Generated by Django 5.1.6 on 2025-06-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_document_doc2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc1',
            new_name='Activity_Proposal',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc2',
            new_name='Budget_Proposal',
        ),
    ]
