# Generated by Django 5.1.6 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_doc1_document_activity_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('completion_processing', 'Completion Processing'), ('completion_recommended', 'Completion Recommended')], default='pending', max_length=30, null=True),
        ),
    ]
