# Generated by Django 5.1.6 on 2025-07-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_chatmessage_options_chatmessage_read_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='day',
            name='document',
        ),
        migrations.RemoveField(
            model_name='day',
            name='extensionists',
        ),
        migrations.RemoveField(
            model_name='daycompletionfile',
            name='day',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='DayCompletionFile',
        ),
    ]
