# Generated by Django 5.1.6 on 2025-08-04 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_document_approved_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name_snapshot',
            field=models.CharField(default='Unknown User', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
