# Generated by Django 5.1.6 on 2025-08-14 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_chatmessage_sender_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
