# Generated by Django 5.0.6 on 2025-09-15 06:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_media_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media_uploads/', validators=[accounts.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video')], default='video', max_length=10),
        ),
    ]
