# Generated by Django 5.0.6 on 2025-09-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_photoalbum_cover_photo_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsPhoto',
        ),
    ]
