# Generated by Django 5.0.6 on 2025-09-19 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_accomplishmentreportpage_departmenttrainingreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttrainingreport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='departmenttrainingreport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departmenttrainingreport',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
