# Generated by Django 5.0.6 on 2025-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_trainingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='weight_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingentry',
            name='weighted_persons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingentry',
            name='quality_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trainingentry',
            name='relevance_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trainingentry',
            name='timeliness_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
