# Generated by Django 5.0.6 on 2025-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_trainingentry_weight_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='total_persons_trained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
