# Generated by Django 5.0.6 on 2025-09-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_trainingentry_total_persons_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='amount_charged_to_partner_agency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingentry',
            name='collaborating_agencies',
            field=models.TextField(blank=True),
        ),
    ]
