# Generated by Django 5.0.6 on 2025-09-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_trainingentry_amount_charged_to_partner_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='venue',
            field=models.TextField(blank=True),
        ),
    ]
