# Generated by Django 5.0.6 on 2025-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_trainingentry_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingentry',
            name='overall_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingentry',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
