# Generated by Django 5.0.6 on 2025-09-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_trainingentry_overall_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day number (1, 2, 3...)')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='accounts.document')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('document', 'day_number')},
            },
        ),
    ]
