# Generated by Django 5.0.6 on 2025-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_documentday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentday',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
