# Generated by Django 5.0.6 on 2025-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_documentday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
