# Generated by Django 5.0.6 on 2025-09-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_documentdaytrainingreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdaytrainingreport',
            name='day',
        ),
        migrations.RemoveField(
            model_name='documentdaytrainingreport',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='DocumentDay',
        ),
        migrations.DeleteModel(
            name='DocumentDayTrainingReport',
        ),
    ]
