# Generated by Django 5.0.6 on 2025-09-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_documentday_daytrainingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTrainingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('number_email', models.CharField(blank=True, max_length=255)),
                ('project_no', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('date_conducted_text', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('male_participants', models.IntegerField(blank=True, null=True)),
                ('female_participants', models.IntegerField(blank=True, null=True)),
                ('total_participants', models.IntegerField(blank=True, null=True)),
                ('student', models.IntegerField(blank=True, null=True)),
                ('farmer', models.IntegerField(blank=True, null=True)),
                ('fisherfolk', models.IntegerField(blank=True, null=True)),
                ('agricultural_technician', models.IntegerField(blank=True, null=True)),
                ('government_employee', models.IntegerField(blank=True, null=True)),
                ('private_employee', models.IntegerField(blank=True, null=True)),
                ('other_category', models.IntegerField(blank=True, null=True)),
                ('total_by_category', models.IntegerField(blank=True, null=True)),
                ('total_persons_trained', models.IntegerField(blank=True, null=True)),
                ('tvl_solo_parent', models.IntegerField(blank=True, null=True)),
                ('tvl_4ps', models.IntegerField(blank=True, null=True)),
                ('tvl_pwd', models.IntegerField(blank=True, null=True)),
                ('tvl_pwd_type', models.CharField(blank=True, max_length=255)),
                ('total_trainees_surveyed', models.IntegerField(blank=True, null=True)),
                ('relevance_counts', models.JSONField(blank=True, default=dict)),
                ('relevance_average', models.FloatField(blank=True, null=True)),
                ('quality_counts', models.JSONField(blank=True, default=dict)),
                ('quality_average', models.FloatField(blank=True, null=True)),
                ('timeliness_counts', models.JSONField(blank=True, default=dict)),
                ('timeliness_average', models.FloatField(blank=True, null=True)),
                ('weight_multiplier', models.FloatField(blank=True, null=True)),
                ('weighted_persons', models.FloatField(blank=True, null=True)),
                ('collaborating_agencies', models.TextField(blank=True)),
                ('amount_charged_to_partner_agency', models.CharField(blank=True, max_length=255)),
                ('venue', models.TextField(blank=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('overall_average', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.daytrainingreport')),
            ],
        ),
    ]
