# Generated by Django 5.0.6 on 2025-09-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_daytrainingentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingentry',
            name='page',
        ),
        migrations.RemoveField(
            model_name='departmenttrainingreport',
            name='page',
        ),
        migrations.RemoveField(
            model_name='departmenttrainingreport',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmenttrainingreport',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='trainingentry',
            name='source_report',
        ),
        migrations.DeleteModel(
            name='AccomplishmentReportPage',
        ),
        migrations.DeleteModel(
            name='DepartmentTrainingReport',
        ),
        migrations.DeleteModel(
            name='TrainingEntry',
        ),
    ]
