# Generated by Django 5.0.6 on 2025-10-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_remove_trainingentry_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='revision_doc8',
            field=models.BooleanField(default=False),
        ),
    ]
