# Generated by Django 5.0.6 on 2025-10-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_documentfile_revision_doc1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc1_label',
            field=models.CharField(default='attendace', max_length=100),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc1_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc2_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc3_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc4_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc5_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc6_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc7_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='completion_doc8_status',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
