# Generated by Django 5.0.6 on 2025-10-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_documentfile_completion_doc1_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Activity_Proposal_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='Budget_Proposal_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc3_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc4_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc5_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc6_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc7_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc8_status',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
