# Generated by Django 5.0.6 on 2025-10-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_document_activity_proposal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc1',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc2',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc3',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc4',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc5',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc6',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc7',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='revision_doc8',
        ),
    ]
