# Generated by Django 5.0.6 on 2025-10-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_remove_documentfile_revision_doc1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Budget_Proposal',
            new_name='Plan_of_Activities',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Budget_Proposal_status',
            new_name='Plan_of_Activities_status',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc3',
            new_name='Work_and_Financial_Plan',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc3_status',
            new_name='Work_and_Financial_Plan_status',
        ),
    ]
