# Generated by Django 5.0.6 on 2025-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_rename_budget_proposal_document_plan_of_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrainingentry',
            name='amount_charged_to_cvsu',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytrainingentry',
            name='amount_charged_to_partner_agency',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
