# Generated by Django 5.0.6 on 2025-10-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_daytrainingentry_amount_charged_to_cvsu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrainingentry',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='daytrainingentry',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
