# Generated by Django 5.0.6 on 2025-10-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_daytrainingentry_coordinator_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.FileField(blank=True, null=True, upload_to='day_documents/')),
                ('doc2', models.FileField(blank=True, null=True, upload_to='day_documents/')),
                ('doc3', models.FileField(blank=True, null=True, upload_to='day_documents/')),
                ('doc4', models.FileField(blank=True, null=True, upload_to='day_documents/')),
                ('doc5', models.FileField(blank=True, null=True, upload_to='day_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_files', to='accounts.documentday')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
