# Generated by Django 5.0.6 on 2025-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_documentdayfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdayfile',
            name='doc1_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdayfile',
            name='doc2_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdayfile',
            name='doc3_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdayfile',
            name='doc4_status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdayfile',
            name='doc5_status',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
