# Generated by Django 5.0.6 on 2025-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_documentdayfile_doc1_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentday',
            old_name='name',
            new_name='title',
        ),
    ]
