# Generated by Django 5.0.6 on 2025-11-06 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_rename_name_documentday_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='revision_feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
