# Generated by Django 5.0.6 on 2025-11-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_documentrevisionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRevisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='day_revision_feedbacks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_feedbacks', to='accounts.documentday')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_revision_feedbacks', to='accounts.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
