# Generated by Django 5.0.6 on 2025-11-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_completionrevisionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrainingentry',
            name='number_of_days_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
